import { library } from '@fortawesome/fontawesome-svg-core';
import { 
  faBell,
  faBars,
  faTimes,
  faChevronDown,
  faSignOutAlt,
  faUser,
  faCog,
  faTachometerAlt,
  faBox,
  faShoppingCart,
  faUsers,
  faChartBar,
  faDollarSign,
  faArrowUp,
  faClock,
  faTruck,
  faCheckCircle,
  faTimesCircle,
  faEye,
  faEdit,
  faTrash,
  faPlus,
  faSearch,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faChevronLeft,
  faChevronRight,
  faUpload,
  faImage,
  faExclamationTriangle,
  faLock,
  faUnlock,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faDollarSign as faDollar,
  faCamera,
  faSave,
  faEyeSlash,
  faHistory,
  faBan,
  faCalendarAlt,
  faCartShopping,
  faHouse,
  faMagnifyingGlass,
  faXmark,
  faCheck,
  faHeart,
  faPaperPlane,
  faRobot,
  faChevronRight as faChevronRightIcon,
  faPhone as faPhoneIcon,
  faEnvelope as faEnvelopeIcon,
  faMapMarkerAlt as faMapMarker,
  faClock as faClockIcon,
  faFacebook,
  faTwitter,
  faInstagram,
  faYoutube,
  faLinkedin,
  faGithub,
  faExclamationCircle,
  faInfoCircle,
  faRefresh,
  faFileExport,
  faSort as faSortIcon
} from '@fortawesome/free-solid-svg-icons';

import {
  faFacebook as faFacebookBrand,
  faTwitter as faTwitterBrand,
  faInstagram as faInstagramBrand,
  faYoutube as faYoutubeBrand,
  faLinkedin as faLinkedinBrand,
  faGithub as faGithubBrand
} from '@fortawesome/free-brands-svg-icons';

// Add all icons to the library
library.add(
  // Solid icons
  faBell,
  faBars,
  faTimes,
  faChevronDown,
  faSignOutAlt,
  faUser,
  faCog,
  faTachometerAlt,
  faBox,
  faShoppingCart,
  faUsers,
  faChartBar,
  faDollarSign,
  faArrowUp,
  faClock,
  faTruck,
  faCheckCircle,
  faTimesCircle,
  faEye,
  faEdit,
  faTrash,
  faPlus,
  faSearch,
  faFilter,
  faSort,
  faSortUp,
  faSortDown,
  faChevronLeft,
  faChevronRight,
  faUpload,
  faImage,
  faExclamationTriangle,
  faLock,
  faUnlock,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faDollar,
  faCamera,
  faSave,
  faEyeSlash,
  faHistory,
  faBan,
  faCalendarAlt,
  faCartShopping,
  faHouse,
  faMagnifyingGlass,
  faXmark,
  faCheck,
  faHeart,
  faPaperPlane,
  faRobot,
  faChevronRightIcon,
  faPhoneIcon,
  faEnvelopeIcon,
  faMapMarker,
  faClockIcon,
  faExclamationCircle,
  faInfoCircle,
  faRefresh,
  faFileExport,
  faSortIcon,
  // Brand icons
  faFacebookBrand,
  faTwitterBrand,
  faInstagramBrand,
  faYoutubeBrand,
  faLinkedinBrand,
  faGithubBrand
);

